"""make episode filename unique

Revision ID: 995172b48d4a
Revises: 86e2ac1deac8
Create Date: 2026-09-03 13:51:46.705191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '995172b48d4a'
down_revision: Union[str, Sequence[str], None] = '86e2ac1deac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'episodes', ['filename'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'episodes', type_='unique')
    # ### end Alembic commands ###
